### ISSUE TITLE
potentiometer to note on

### ISSUE THREAD

**Issue by RocktorT** [arduino-libraries/MIDIUSB#103]
Hi!
How can you send a messages "note on" when rotating a potentiometer?

**Comment by per1234** [comment]
Hi @RocktorT. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
