### ISSUE TITLE
[QUESTION] Alternative for other boards?

### ISSUE THREAD

**Issue by EncryptEx** [arduino-libraries/MIDIUSB#107]
Hi, I'm interested into this library but unluckily I own a UNO and a MEGA Arduino boards,
is there any alternatives for non-USB based boards?

**Comment by per1234** [comment]
Hi @EncryptEx. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
