### ISSUE TITLE
Compile error for Pi Pico

### ISSUE THREAD

**Issue by w9ran** [arduino-libraries/MIDIUSB#108]
Surprised to get this error when compiling the CCRotaryEncoder example.

Since Raspberry Pi Pico is shown as a supported platform, I'd appreciate any  suggested workaround for the encoder interrupts.   (Is the "kludge" recommended?

Thanks.   Here is the complete error message string:

```text
In file included from C:\Users\ranic\Documents\Arduino\libraries\Encoder/Encoder.h:46:0,
                 from C:\Users\ranic\Downloads\Control-Surface-main\Control-Surface-main\examples.old\medium-old\MIDIOutput\Control-Change\CCRotaryEncoder\CCRotaryEncoder.ino:29:
C:\Users\ranic\Documents\Arduino\libraries\Encoder/utility/interrupt_pins.h:334:2: error: #error "Interrupts are unknown for this board, please add to this code"
 #error "Interrupts are unknown for this board, please add to this code"
  ^~~~~
C:\Users\ranic\Documents\Arduino\libraries\Encoder/utility/interrupt_pins.h:337:2: error: #error "Encoder requires interrupt pins, but this board does not have any :("
 #error "Encoder requires interrupt pins, but this board does not have any :("
  ^~~~~
C:\Users\ranic\Documents\Arduino\libraries\Encoder/utility/interrupt_pins.h:338:2: error: #error "You could try defining ENCODER_DO_NOT_USE_INTERRUPTS as a kludge."
 #error "You could try defining ENCODER_DO_NOT_USE_INTERRUPTS as a kludge."
  ^~~~~
Using library Encoder at version 1.4.2 in folder: C:\Users\ranic\Documents\Arduino\libraries\Encoder 
Using library Control-Surface-main at version 2.0.0 in folder: C:\Users\ranic\Documents\Arduino\libraries\Control-Surface-main 
Using library SPI in folder: C:\Users\ranic\AppData\Local\Arduino15\packages\arduino\hardware\mbed_rp2040\3.1.1\libraries\SPI (legacy)
exit status 1
Error compiling for board Raspberry Pi Pico.
```

**Comment by per1234** [comment]
Hi @w9ran. Thanks for your interest in this open source project. This is the repository for the "MIDIUSB" library. The compilation error you are experiencing is from the "Encoder' library, which is a 3rd party library completely separate from the "MIDIUSB" library. The "CCRotaryEncoder" sketch you are compiling is also a 3rd party project not part of this repository.

So I will close this as off topic for this issue tracker.

I recommend posting about your problem over on Arduino Forum:

https://forum.arduino.cc/c/using-arduino/programming-questions/20

I'm sure we'll be able to help you out over there.
