### ISSUE TITLE
Problems with the endpoints?

### ISSUE THREAD

**Issue by paulobarcelos** [arduino-libraries/MIDIUSB#11]
Hi, I noticed I could not get the examples to work when running the code from master or version 1.0.1 from Arduino's library manager.

But If I use version 1.0.0 it works fine...

I've noticed the problem on Windows 7, 8, 10, OSX 10.6 and 10.11, and IOS 9.0. I've tested with Arduino micro plugged with the "loop" and "write" examples. I could se the in and out MIDI ports being enumerated, but could not receive any messages. 

I've reverted `EP_TYPE_BULK_OUT_MIDI` and `EP_TYPE_BULK_IN_MIDI` on `MIDIUSB.h` to:

````
#define EP_TYPE_BULK_OUT_MIDI		EP_TYPE_BULK_OUT
#define EP_TYPE_BULK_IN_MIDI		EP_TYPE_BULK_IN
````
and it started working again... at least on my OSX El Capitan. (don't have have access to the other platforms right now).

**Comment by facchinm** [comment]
Hi @paulobarcelos ,
thanks for pointing it out!
Solved with c491a9c34c222eacf679bee9f312238db8d89690
