### ISSUE TITLE
Due USB Name change

### ISSUE THREAD

**Issue by RezaYazdi604** [arduino-libraries/MIDIUSB#114]
Hi

I'm using this library for making a MIDI controller with Arduino Due. 
I want to change the name of the native USB port on my Due to show a custom name when connected to PC.
Does anyone here know how to do this for Due? 

I've seen it that they can do it for other AVR boards but nor for Due. 

Appreciate any help and guidance.
Thanks

**Comment by per1234** [comment]
Hi @RezaYazdi604. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/

**Comment by RezaYazdi604** [comment]
Thank you. I’ve posted my problem on that forum too. Hopefully someone can help. If you know any previous posts to address my problem please point me there. Thanks again.  Cheers,RezaOn May 18, 2024, at 11:49 PM, per1234 ***@***.***> wrote:﻿
Hi @RezaYazdi604. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:
https://forum.arduino.cc/
