### ISSUE TITLE
midiUSB.available()

### ISSUE THREAD

**Issue by cadupalmieri** [arduino-libraries/MIDIUSB#117]
This function dot work for me, always return 0;

How to make this funcional ?

**Comment by per1234** [comment]
Hi @cadupalmieri. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
