### ISSUE TITLE
Arduino/Genuino 101

### ISSUE THREAD

**Issue by Pachicito** [arduino-libraries/MIDIUSB#17]
Hello,

It appears this library doesn't support the newer Arduino/Genuino 101 due to it having an ARC core instead of an AVR core. Will this library be updated to work with the new breed of boards?

Thanks!

**Comment by facchinm** [comment]
Hi @Pachicito ,
at the moment the 101 core (x86 + ARC) doesn't support additional USB profiles, thus we can't port `PluggableUSB` (and `MIDIUSB`) to that core. 
The peculiar architecture of the chip makes this feature really difficult to code even in distant future so don't hold breath :wink:
