### ISSUE TITLE
Will this work with Arduino Leonardo?

### ISSUE THREAD

**Issue by sanotronics** [arduino-libraries/MIDIUSB#18]
Hello! 

Just wondering if this lib will work with Atmega32u4.

I don't have one to test it myself, but I am thinking of a product and would love to know if this will help me.

Thanks!

**Comment by NicoHood** [comment]
If not with the 32u4, what else?

**Comment by sanotronics** [comment]
I was wondering actually if it only worked with the new arduinos, with ARM cores (due, zero) or if it'd also work with the leonardo.

**Comment by monteslu** [comment]
Works great on a Leonardo

**Comment by sandeepmistry** [comment]
@monteslu thanks for confirming it works with the Leonardo!
