### ISSUE TITLE
Error compiling the example sketch

### ISSUE THREAD

**Issue by blackTay** [arduino-libraries/MIDIUSB#20]
When I try compiling the example sketch in Arduino 1.6.8 for an Arduino Uno, I get this error:

>  #error MIDIUSB can only be used with an USB MCU.
> exit status 1

Is it an error in the library?

**Comment by facchinm** [comment]
Hi @blackTay , the UNO microcontroller doesn't come with native USB so the library is not compatible with that board. Boards based on 32u4 chip (like Micro) or newer boards (Zero, MKR1000) instead are ok. You can still use MIDI over serial (there are a lot of libraries to do so) or hack the UNO communication microcontroller to do MIDI over USB (check out [this](https://github.com/ddiakopoulos/hiduino) project)
