### ISSUE TITLE
Multi port devices.....

### ISSUE THREAD

**Issue by fraramon** [arduino-libraries/MIDIUSB#27]
Is there any way to have arduino leonardo or arduino zero .... multi port device ... Example ....
Midi1
Midi2
Midi3
Mouse
With only one card ....
Thank you very much.....

**Comment by facchinm** [comment]
Hi @fraramon ,
you can instantiate other objects of type `MIDI_`  simply with
```C++
MIDI_ Midi1;
```
in your sketch. However, every object will occupy 2 endpoints (there are 6 in Leonardo's 32u4) and 3 are already taken by CDC Serial. So adding more MIDI interfaces is only possible with newer boards like Arduino Zero.
