### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by vjdobermann** [arduino-libraries/MIDIUSB#38]
Hi team,

I try to use this library but when I want to upload my code to my arduino uno, I get this error message 👍 

In file included from /Users/vjdobermann/Documents/Arduino/push_button_midi/push_button_midi.ino:2:0:
/Users/vjdobermann/Documents/Arduino/libraries/MIDIUSB-master/src/MIDIUSB.h:18:2: error: #error MIDIUSB can only be used with an USB MCU.
 #error MIDIUSB can only be used with an USB MCU.
  ^
exit status 1
Erreur de compilation pour la carte Arduino/Genuino Uno

Could someone help me please ?

**Comment by fab672000** [comment]
Your MCU for the Uno is an atmega328p which is not a USB MCU. So as it states ; it won't work because MIDIUSB needs a USB MCU like on the arduino: leonardo, (pro) micro, Zero or Due.

**Comment by vjdobermann** [comment]
Hi fab,
thanks for you answer.
In my project I need to use a midi signal, is still possible to send midi over usb câble with the Uno ?

**Comment by fab672000** [comment]
Yes it is possible,  but you need a different _software_  usb library with a dedicated bootstrap like [hiduino ](https://github.com/ddiakopoulos/hiduino) (you will need to upload the code with a programmer).

**Comment by vjdobermann** [comment]
oh does it exist a solution more simple ?
Or it's definitely impossible to send out midi signal from an uno ?

**Comment by per1234** [comment]
No it's not impossible. @fab672000 already explained how it can be done. It's not simple. Just buy an Arduino Leonardo or Pro Micro.

**Comment by vjdobermann** [comment]
finally I've founded a solution with this [http://projectgus.github.io/hairless-midiserial/#getting_started](http://projectgus.github.io/hairless-midiserial/#getting_started)

**Comment by facchinm** [comment]
It's a sort of workaround but it definitely works ;) I'm closing the issue as solved, thanks!
