### ISSUE TITLE
Note board limitations in documentation

### ISSUE THREAD

**Issue by awgrover** [arduino-libraries/MIDIUSB#42]
It looks like this library will only work for certain arduino boards. Maybe the same limitations as noted in https://www.arduino.cc/en/Reference/MouseKeyboard ? Adding a note to the README would be nice.

**Comment by facchinm** [comment]
Hi @awgrover ,
the reference you mentioned specifies
```
These core libraries allow a 32u4 based boards or Due and Zero board to appear as a native Mouse and/or Keyboard to a connected computer.
```
It should be enough, although I think we just need a better periphrasis to describe boards (processors) with native USB capabilities.

**Comment by facchinm** [comment]
Sorry, I totally misinterpreted the issue. I'm adding some info on README to make it super clear
