### ISSUE TITLE
"controlChange" part seems misplaced in the examples?

### ISSUE THREAD

**Issue by glennjacobsen** [arduino-libraries/MIDIUSB#45]
Might just be me not getting this, but why is the controlChange function placed under "setup" while the others are placed over?

Also, "controlChange" refers to "event" and not to "controlChange" in the examples, midi read f.ex.

**Comment by facchinm** [comment]
In Arduino you don't need to declare the functions before using them, so they can be placed everywhere. If you are compiling in another framework, move it before its first use. 
About examples, `MIDIUSB_read`, `MIDIUSB_write` and `MIDIUSB_loop` only show the API usage, so they are not really useful;  `MIDIUSB_buzzer` can instead be used to understand how to use the library for real.
