### ISSUE TITLE
ATmega2560 ATMEGA16U2 Support?

### ISSUE THREAD

**Issue by JuniorGamingTime** [arduino-libraries/MIDIUSB#53]
Is there a way to use this board? i need a lot of buttons and knobs

**Comment by facchinm** [comment]
Hi @JuniorGamingTime ,
to use this library on the 16u2 you must first reprogram it with something like https://github.com/NicoHood/HoodLoader2 ; then you can communicate between the 16u2 and the 2560 using the internal serial port.

**Comment by fab672000** [comment]
> Is there a way to use this board? i need a lot of buttons and knobs

Or you can use an atmega16u4 with a great i2c to serial i/o chio such as the 2317 (or 23s17 if you want his-speed but it takes more wires to connect it: [look here](http://ww1.microchip.com/downloads/en/devicedoc/21952a.pdf)
