### ISSUE TITLE
how to write 0xF events via MidiUSB.send()?

### ISSUE THREAD

**Issue by 2kohm** [arduino-libraries/MIDIUSB#59]
Hello,

is it possible so send Midi Clock pules ?

trying to make a midi clock and want to send these midi messages

// Clock start = 0xFA
// Clock stop = 0xFC
// Clock pulse = 0xF8

` MidiUSB.send(0xF8); `

**Comment by thekunalsaini** [comment]
Hello @2kohm,
It is possible to send it.

**Comment by samisabik** [comment]
you need to specify the MIDI header for real-time messages : 0x0F
`midiEventPacket_t clock = {0x0F,0xF8,0,0};`

**Comment by samisabik** [comment]
However related to this question, I'm having some issue formating the real-time MIDI packet to specify the channel.
