### ISSUE TITLE
MKR1010 won't show up as USB MIDI device

### ISSUE THREAD

**Issue by ArteFrancoMolina** [arduino-libraries/MIDIUSB#60]
I'm trying to test the MIDIUSB_write example sketch on a MKR wifi 1010, but after uploading it to the board, it doesn't get recognized by my computer as a MIDI device, no matter what software or DAW I tried to use. It also stops being recognized by the Arduino IDE until I reset it with a double tap on the on-board button.

As far as I know, this board has USB capabilities, and the library is designed for samd architectures too. I've reinstalled and updated the IDE and the board both with firmware update and with the boards manager. The board is brand new and works fine when I test the blink and other simple sketches.

What am I missing? I hope I'm not asking a question asked a million times before. I tried to look for info online, but there's not much info about this board in relation to this kind of libraries.

Thanks.

**Comment by facchinm** [comment]
Hi @ArteFrancoMolina ,
if you are on Windows, it may happen that the drivers for the new composite device are not getting loaded correctly. Try uninstalling all the drivers currently loaded with the board (from Device Manager) and if you are on windows 10 it should reinstall the correct ones.
For further explanation, please read this thread that almost completely applies (https://github.com/webusb/arduino/issues/44)
