### ISSUE TITLE
Need help for led & button

### ISSUE THREAD

**Issue by 4dvn** [arduino-libraries/MIDIUSB#64]
Hello, i have a native rgb midi lightstrip code wanna add 16 buttons code to work like Novation Launchpad, anyone know how to add midi buttons code from note 36-51?
Here is my project:
https://github.com/4dvn/Leonardo-Underlights/blob/master/Leonardo/WS2812B/WS2812B.ino

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
