### ISSUE TITLE
Como crear puertos virtuales midi

### ISSUE THREAD

**Issue by Veroledez** [arduino-libraries/MIDIUSB#80]
Hola, me preguntaba si hay forma de crear puertos virtuales midi en placas como la samd21 u otras. Se que en teensy se pueden crear hasta 16 puertos virtuales midi, pero en otras placas no se como se implementan.  Entonces como hago o hay limitaciones en las placas para hacer esto, y solo es caracteristica de teensy.

Muchas gracias.

**Comment by per1234** [comment]
Hi @Veroledez. Thanks for your interest in this open source project. This topic seems to be more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/c/international/espanol/48
