### ISSUE TITLE
Transport Messages (topic: question)

### ISSUE THREAD

**Issue by SteeveDess** [arduino-libraries/MIDIUSB#81]
Hi,

I'm interested to build a usb midi pedalboard to control studio one show page on foot, with midi message like play, stop, record, rewind and forward.
I have an arduino pro micro ATmega32U4 board.
I tested the example to send midi notes, It's working well. My windows 10 and studio one recognized the midi device, and received the note (on and off) messages. Great and simple.

Now, I'd like to send the transports messages, starting with a simple play, wait, stop, wait, scenario.

It's not clear that it's possible with this library, is it ?

A comment in this topic https://github.com/arduino-libraries/MIDIUSB/issues/48 talk about another library that correct the trouble (https://github.com/lathoub/Arduino-USBMIDI)

It's not clear for me how to do it.

I like this MIDIUSB library for it simplicity to use, I'd like some intels about how to send transport messages 

Regards,
Steeve

**Comment by per1234** [comment]
Hi @SteeveDess. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum, where we have a section dedicated to assistance for Arduino projects with MIDI. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/c/using-arduino/audio/24
