### ISSUE TITLE
How to use physical MIDI din with the USB

### ISSUE THREAD

**Issue by silveirago** [arduino-libraries/MIDIUSB#87]
I have been trying to find the documentation about how to use physical MIDI din together with the USB, if it is possible and how to do it, but no luck yet. Any help?

**Comment by per1234** [comment]
Hi @silveirago. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/c/using-arduino/audio/24
